*File created from weatheryear module
$onMulti
SET ALLOWEDINV(AAA,GGG) 
/ 
IE_OFF_VRE-OFF_bottom_fixed_SP316-HH155_RG1.( 
GNR_WT-SP316-HH155_OFF_bottom_fixed_RG1_Y-2020
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG1_Y-2030
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG1_Y-2040
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG1_Y-2050
 ) 
 
IE_OFF_VRE-OFF_bottom_fixed_SP316-HH155_RG2.( 
GNR_WT-SP316-HH155_OFF_bottom_fixed_RG2_Y-2020
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG2_Y-2030
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG2_Y-2040
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG2_Y-2050
 ) 
 
IE_OFF_VRE-OFF_bottom_fixed_SP316-HH155_RG3.( 
GNR_WT-SP316-HH155_OFF_bottom_fixed_RG3_Y-2020
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG3_Y-2030
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG3_Y-2040
 GNR_WT-SP316-HH155_OFF_bottom_fixed_RG3_Y-2050
 ) 
 
IE_OFF_VRE-OFF_bottom_fixed_SP370-HH155_RG1.( 
GNR_WT-SP370-HH155_OFF_bottom_fixed_RG1_Y-2020
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG1_Y-2030
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG1_Y-2040
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG1_Y-2050
 ) 
 
IE_OFF_VRE-OFF_bottom_fixed_SP370-HH155_RG2.( 
GNR_WT-SP370-HH155_OFF_bottom_fixed_RG2_Y-2020
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG2_Y-2030
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG2_Y-2040
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG2_Y-2050
 ) 
 
IE_OFF_VRE-OFF_bottom_fixed_SP370-HH155_RG3.( 
GNR_WT-SP370-HH155_OFF_bottom_fixed_RG3_Y-2020
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG3_Y-2030
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG3_Y-2040
 GNR_WT-SP370-HH155_OFF_bottom_fixed_RG3_Y-2050
 ) 
 
IE_VRE-ONS_SP199-HH150_RG1.( 
GNR_WT-SP199-HH150_ONS_RG1_Y-2020
 GNR_WT-SP199-HH150_ONS_RG1_Y-2030
 GNR_WT-SP199-HH150_ONS_RG1_Y-2040
 GNR_WT-SP199-HH150_ONS_RG1_Y-2050
 ) 
 
IE_VRE-ONS_SP199-HH150_RG2.( 
GNR_WT-SP199-HH150_ONS_RG2_Y-2020
 GNR_WT-SP199-HH150_ONS_RG2_Y-2030
 GNR_WT-SP199-HH150_ONS_RG2_Y-2040
 GNR_WT-SP199-HH150_ONS_RG2_Y-2050
 ) 
 
IE_VRE-ONS_SP199-HH150_RG3.( 
GNR_WT-SP199-HH150_ONS_RG3_Y-2020
 GNR_WT-SP199-HH150_ONS_RG3_Y-2030
 GNR_WT-SP199-HH150_ONS_RG3_Y-2040
 GNR_WT-SP199-HH150_ONS_RG3_Y-2050
 ) 
 
IE_VRE-ONS_SP199-HH100_RG1.( 
GNR_WT-SP199-HH100_ONS_RG1_Y-2020
 GNR_WT-SP199-HH100_ONS_RG1_Y-2030
 GNR_WT-SP199-HH100_ONS_RG1_Y-2040
 GNR_WT-SP199-HH100_ONS_RG1_Y-2050
 ) 
 
IE_VRE-ONS_SP199-HH100_RG2.( 
GNR_WT-SP199-HH100_ONS_RG2_Y-2020
 GNR_WT-SP199-HH100_ONS_RG2_Y-2030
 GNR_WT-SP199-HH100_ONS_RG2_Y-2040
 GNR_WT-SP199-HH100_ONS_RG2_Y-2050
 ) 
 
IE_VRE-ONS_SP199-HH100_RG3.( 
GNR_WT-SP199-HH100_ONS_RG3_Y-2020
 GNR_WT-SP199-HH100_ONS_RG3_Y-2030
 GNR_WT-SP199-HH100_ONS_RG3_Y-2040
 GNR_WT-SP199-HH100_ONS_RG3_Y-2050
 ) 
 
IE_VRE-ONS_SP277-HH100_RG1.( 
GNR_WT-SP277-HH100_ONS_RG1_Y-2020
 GNR_WT-SP277-HH100_ONS_RG1_Y-2030
 GNR_WT-SP277-HH100_ONS_RG1_Y-2040
 GNR_WT-SP277-HH100_ONS_RG1_Y-2050
 ) 
 
IE_VRE-ONS_SP277-HH100_RG2.( 
GNR_WT-SP277-HH100_ONS_RG2_Y-2020
 GNR_WT-SP277-HH100_ONS_RG2_Y-2030
 GNR_WT-SP277-HH100_ONS_RG2_Y-2040
 GNR_WT-SP277-HH100_ONS_RG2_Y-2050
 ) 
 
IE_VRE-ONS_SP277-HH100_RG3.( 
GNR_WT-SP277-HH100_ONS_RG3_Y-2020
 GNR_WT-SP277-HH100_ONS_RG3_Y-2030
 GNR_WT-SP277-HH100_ONS_RG3_Y-2040
 GNR_WT-SP277-HH100_ONS_RG3_Y-2050
 ) 
 
IE_VRE-PV_Utility_scale_no_tracking_RG1.( 
GNR_PV-Utility_scale_no_tracking_RG1_Y-2020
 GNR_PV-Utility_scale_no_tracking_RG1_Y-2030
 GNR_PV-Utility_scale_no_tracking_RG1_Y-2040
 GNR_PV-Utility_scale_no_tracking_RG1_Y-2050
 GNR_PV-Utility_scale_no_tracking_RG1_Existing
 ) 
 
IE_VRE-PV_Utility_scale_no_tracking_RG2.( 
GNR_PV-Utility_scale_no_tracking_RG2_Y-2020
 GNR_PV-Utility_scale_no_tracking_RG2_Y-2030
 GNR_PV-Utility_scale_no_tracking_RG2_Y-2040
 GNR_PV-Utility_scale_no_tracking_RG2_Y-2050
 GNR_PV-Utility_scale_no_tracking_RG2_Existing
 ) 
 
IE_VRE-PV_Utility_scale_no_tracking_RG3.( 
GNR_PV-Utility_scale_no_tracking_RG3_Y-2020
 GNR_PV-Utility_scale_no_tracking_RG3_Y-2030
 GNR_PV-Utility_scale_no_tracking_RG3_Y-2040
 GNR_PV-Utility_scale_no_tracking_RG3_Y-2050
 GNR_PV-Utility_scale_no_tracking_RG3_Existing
 ) 
 
IE_VRE-PV_Utility_scale_tracking_RG1.( 
GNR_PV-Utility_scale_tracking_RG1_Y-2020
 GNR_PV-Utility_scale_tracking_RG1_Y-2030
 GNR_PV-Utility_scale_tracking_RG1_Y-2040
 GNR_PV-Utility_scale_tracking_RG1_Y-2050
 GNR_PV-Utility_scale_tracking_RG1_Existing
 ) 
 
IE_VRE-PV_Utility_scale_tracking_RG2.( 
GNR_PV-Utility_scale_tracking_RG2_Y-2020
 GNR_PV-Utility_scale_tracking_RG2_Y-2030
 GNR_PV-Utility_scale_tracking_RG2_Y-2040
 GNR_PV-Utility_scale_tracking_RG2_Y-2050
 GNR_PV-Utility_scale_tracking_RG2_Existing
 ) 
 
IE_VRE-PV_Utility_scale_tracking_RG3.( 
GNR_PV-Utility_scale_tracking_RG3_Y-2020
 GNR_PV-Utility_scale_tracking_RG3_Y-2030
 GNR_PV-Utility_scale_tracking_RG3_Y-2040
 GNR_PV-Utility_scale_tracking_RG3_Y-2050
 GNR_PV-Utility_scale_tracking_RG3_Existing
 ) 
 
/ ;

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'OFF_Existing_RG1')=1)  and ALLOWEDINV('IE_OFF_OFF_Existing_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'OFF_Existing_RG2')=1)  and ALLOWEDINV('IE_OFF_OFF_Existing_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'OFF_Existing_RG3')=1)  and ALLOWEDINV('IE_OFF_OFF_Existing_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'ONS_Existing_RG1')=1)  and ALLOWEDINV('IE_ONS_Existing_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'ONS_Existing_RG2')=1)  and ALLOWEDINV('IE_ONS_Existing_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'ONS_Existing_RG3')=1)  and ALLOWEDINV('IE_ONS_Existing_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-OFF_bottom_fixed_SP316-HH155_RG1')=1)  and ALLOWEDINV('IE_OFF_VRE-OFF_bottom_fixed_SP316-HH155_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-OFF_bottom_fixed_SP316-HH155_RG2')=1)  and ALLOWEDINV('IE_OFF_VRE-OFF_bottom_fixed_SP316-HH155_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-OFF_bottom_fixed_SP316-HH155_RG3')=1)  and ALLOWEDINV('IE_OFF_VRE-OFF_bottom_fixed_SP316-HH155_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-OFF_bottom_fixed_SP370-HH155_RG1')=1)  and ALLOWEDINV('IE_OFF_VRE-OFF_bottom_fixed_SP370-HH155_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-OFF_bottom_fixed_SP370-HH155_RG2')=1)  and ALLOWEDINV('IE_OFF_VRE-OFF_bottom_fixed_SP370-HH155_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-OFF_bottom_fixed_SP370-HH155_RG3')=1)  and ALLOWEDINV('IE_OFF_VRE-OFF_bottom_fixed_SP370-HH155_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP199-HH150_RG1')=1)  and ALLOWEDINV('IE_VRE-ONS_SP199-HH150_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP199-HH150_RG2')=1)  and ALLOWEDINV('IE_VRE-ONS_SP199-HH150_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP199-HH150_RG3')=1)  and ALLOWEDINV('IE_VRE-ONS_SP199-HH150_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP199-HH100_RG1')=1)  and ALLOWEDINV('IE_VRE-ONS_SP199-HH100_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP199-HH100_RG2')=1)  and ALLOWEDINV('IE_VRE-ONS_SP199-HH100_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP199-HH100_RG3')=1)  and ALLOWEDINV('IE_VRE-ONS_SP199-HH100_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP277-HH100_RG1')=1)  and ALLOWEDINV('IE_VRE-ONS_SP277-HH100_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP277-HH100_RG2')=1)  and ALLOWEDINV('IE_VRE-ONS_SP277-HH100_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'VRE-ONS_SP277-HH100_RG3')=1)  and ALLOWEDINV('IE_VRE-ONS_SP277-HH100_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'PV_Utility_scale_no_tracking_RG1')=1)  and ALLOWEDINV('IE_VRE-PV_Utility_scale_no_tracking_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'PV_Utility_scale_no_tracking_RG2')=1)  and ALLOWEDINV('IE_VRE-PV_Utility_scale_no_tracking_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'PV_Utility_scale_no_tracking_RG3')=1)  and ALLOWEDINV('IE_VRE-PV_Utility_scale_no_tracking_RG3',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'PV_Utility_scale_tracking_RG1')=1)  and ALLOWEDINV('IE_VRE-PV_Utility_scale_tracking_RG1',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'PV_Utility_scale_tracking_RG2')=1)  and ALLOWEDINV('IE_VRE-PV_Utility_scale_tracking_RG2',G))         = yes ; 

ALLOWEDINV(AAA,G)$((INVDATA(AAA,'PV_Utility_scale_tracking_RG3')=1)  and ALLOWEDINV('IE_VRE-PV_Utility_scale_tracking_RG3',G))         = yes ; 