TABLE DH(YYY, AAA, DHUSER) 'Annual heat consumption (MWh)'
                                IND-PHH       IND-PHL       IND-PHM           RESH    RESIDENTIAL
                                                                                                 
2019 . CL0_A                                                         11199715.0172               
2019 . CL0_IDVU-SPACEHEAT                                                           10350082.1768
2019 . CL0_IND-HT-NODH     2411594.2709                                                          
2019 . CL0_IND-LT-NODH                    2392449.484                                            
2019 . CL0_IND-MT-NODH                                 797483.16377                              
2019 . CL1_A                                                          16186167.246               
2019 . CL1_IDVU-SPACEHEAT                                                           16210706.0694
2019 . CL1_IND-HT-NODH     5615203.6939                                                          
2019 . CL1_IND-LT-NODH                   6200993.3573                                            
2019 . CL1_IND-MT-NODH                                 2066997.6707                              
2050 . CL0_A                                                         11199715.0172               
2050 . CL0_IDVU-SPACEHEAT                                                           10350082.1768
2050 . CL0_IND-HT-NODH     2411594.2709                                                          
2050 . CL0_IND-LT-NODH                    2392449.484                                            
2050 . CL0_IND-MT-NODH                                 797483.16377                              
2050 . CL1_A                                                          16186167.246               
2050 . CL1_IDVU-SPACEHEAT                                                           16210706.0694
2050 . CL1_IND-HT-NODH     5615203.6939                                                          
2050 . CL1_IND-LT-NODH                   6200993.3573                                            
2050 . CL1_IND-MT-NODH                                 2066997.6707                              
;