PARAMETER DISCOST_E(RRR) 'Cost of electricity distribution (Money/MWh)'

/
        
        
AL   5.0
AT   5.0
BA   5.0
BE   5.0
BG   5.0
CH   5.0
CZ   5.0
DE   5.0
DK   5.0
EE   5.0
ES   5.0
FI   5.0
FR   5.0
GR   5.0
HR   5.0
HU   5.0
IE   5.0
IT   5.0
LT   5.0
LU   5.0
LV   5.0
ME   5.0
MK   5.0
NL   5.0
NO   5.0
PL   5.0
PT   5.0
RO   5.0
ROW  5.0
RS   5.0
SE   5.0
SI   5.0
SK   5.0
UK   5.0
/;
