PARAMETER DISLOSS_E(RRR) 'Loss in electricity distribution (fraction)'

/
             
             
AL       0.05
AT       0.05
BA       0.05
BE       0.05
BG       0.05
CH       0.05
CZ       0.05
DE   0.048286
DK   0.041055
EE       0.05
ES       0.05
FI   0.021299
FR       0.05
GR       0.05
HR       0.05
HU       0.05
IE       0.05
IT       0.05
LT       0.05
LU       0.05
LV       0.05
ME       0.05
MK       0.05
NL   0.029597
NO   0.049694
PL       0.05
PT       0.05
RO       0.05
ROW      0.05
RS       0.05
SE   0.056333
SI       0.05
SK       0.05
UK     0.0803
/;
