TABLE FUELTRANSPORT_COST(FFF, IRRRE, IRRRI) 'Cost of transporting one GJ of fuel F from region IRRRE to IRRRI'
                     CL0          CL1          CL2          CL3          CL4          CL5          CL6         CL7          CL8          CL9
                                                                                                                                            
STRAW . CL0          0.0                1360.63251                622.912232               2036.722224                            802.952394
STRAW . CL1                       0.0  4203.558838                                                                                          
STRAW . CL2   1360.63251  4203.558838          0.0               1631.352274  1317.252188                                        1364.836363
STRAW . CL3                                                 0.0                            2617.808199                                      
STRAW . CL4   622.912232               1631.352274                       0.0                                        1063.145083             
STRAW . CL5                            1317.252188                                                                                          
STRAW . CL6  2036.722224                            2617.808199                                    0.0  730.035283                          
STRAW . CL7                                                                                 730.035283                                      
STRAW . CL8                                                      1063.145083                                                                
STRAW . CL9   802.952394               1364.836363                                                                                          
;