TABLE FUELTRANSPORT_COST(FFF, IRRRE, IRRRI) 'Cost of transporting one GJ of fuel F from region IRRRE to IRRRI'
                     CL0          CL1          CL2          CL3          CL4          CL5         CL6        CL7         CL8          CL9
                                                                                                                                         
STRAW . CL0          EPS  3429.685497                              937.02186                                      404.789845  2167.788757
STRAW . CL1  3429.685497          EPS  1631.352274               3266.536978                                      912.462343             
STRAW . CL2               1631.352274          EPS                            1500.807502                                                
STRAW . CL3                                                 EPS               2617.808199                                                
STRAW . CL4    937.02186  3266.536978                                    EPS                                                             
STRAW . CL5                            1500.807502  2617.808199                       EPS  702.615922                                    
STRAW . CL6                                                                    702.615922              27.419361                         
STRAW . CL7                                                                                 27.419361                                    
STRAW . CL8   404.789845   912.462343                                                                                                    
STRAW . CL9  2167.788757                                                                                                                 
;