TABLE FUELTRANSPORT_COST(FFF, IRRRE, IRRRI) 'Cost of transporting one GJ of fuel F from region IRRRE to IRRRI'
                  CL0       CL1       CL2       CL3       CL4       CL5       CL6       CL7       CL8       CL9
                                                                                                               
STRAW . CL0       0.0            0.164113  2.617808  0.460867                                                  
STRAW . CL1                 0.0                      0.502994                      0.433558  0.329313  0.364433
STRAW . CL2  0.164113                 0.0                      0.117103                                        
STRAW . CL3  2.617808                           0.0                                                            
STRAW . CL4  0.460867  0.502994                           0.0                                          0.539771
STRAW . CL5                      0.117103                                0.027419                              
STRAW . CL6                                                    0.027419                                        
STRAW . CL7            0.433558                                                                                
STRAW . CL8            0.329313                                                                                
STRAW . CL9            0.364433                      0.539771                                               0.0
WOOD . CL0        0.0            0.164113  2.617808  0.460867                                                  
WOOD . CL1                  0.0                      0.502994                      0.433558  0.329313  0.364433
WOOD . CL2   0.164113                 0.0                      0.117103                                        
WOOD . CL3   2.617808                           0.0                                                            
WOOD . CL4   0.460867  0.502994                           0.0                                          0.539771
WOOD . CL5                       0.117103                                0.027419                              
WOOD . CL6                                                     0.027419                                        
WOOD . CL7             0.433558                                                                                
WOOD . CL8             0.329313                                                                                
WOOD . CL9             0.364433                      0.539771                                               0.0
;