TABLE GMAXF(YYY, CCCRRRAAA, FFF) 'Maximum fuel use (GJ) per year'
                    BIOGAS MUNIWASTE         STRAW          WOOD WOODCHIPS    WOODPELLETS WOODWASTE
                                                                                                   
2050 . CL0                            3.848345e+07  3.083844e+07             6.075949e+07          
2050 . CL1                            1.551655e+07  9.161564e+06             1.518987e+07          
2050 . DENMARK  10560000.0  763308.0  5.400000e+07  4.000000e+07       0.0  4.940656e-324       0.0
;