TABLE GMAXF(YYY, CCCRRRAAA, FFF) 'Maximum fuel use (GJ) per year'
                    BIOGAS MUNIWASTE            STRAW             WOOD WOODCHIPS WOODPELLETS WOODWASTE
                                                                                                      
2050 . CL0                            15502349.711733  12872810.010639                   EPS          
2050 . CL1                            12763764.064457   9991555.740416                   EPS          
2050 . CL2                            16289900.641034  10374394.574938            15189873.0          
2050 . CL3                               603575.31777              EPS                   EPS          
2050 . CL4                             2210191.005435   2372363.092632            15189873.0          
2050 . CL5                             4511371.190854   2824068.205317                   EPS          
2050 . CL6                                        EPS              EPS            15189873.0          
2050 . CL7                                        EPS              EPS                   EPS          
2050 . CL8                              689162.337628    463919.926549            15189873.0          
2050 . CL9                             1429685.731088   1100888.449508            15189873.0          
2050 . DENMARK  10560000.0  763308.0       54000000.0       40000000.0       EPS         EPS       EPS
;