TABLE GMAXF(YYY, CCCRRRAAA, FFF) 'Maximum fuel use (GJ) per year'
                    BIOGAS MUNIWASTE          STRAW           WOOD WOODCHIPS WOODWASTE
                                                                                      
2050 . CL0                             1.550235e+07   1.287281e+07                    
2050 . CL1                             1.276376e+07   9.991556e+06                    
2050 . CL2                             1.628990e+07   1.037439e+07                    
2050 . CL3                             6.035753e+05            EPS                    
2050 . CL4                             2.210191e+06   2.372363e+06                    
2050 . CL5                             4.511371e+06   2.824068e+06                    
2050 . CL6                                      EPS            EPS                    
2050 . CL7                                      EPS            EPS                    
2050 . CL8                             6.891623e+05   4.639199e+05                    
2050 . CL9                             1.429686e+06   1.100888e+06                    
2050 . DENMARK  10560000.0  763308.0   5.400000e+07   4.000000e+07       0.0       0.0
;