TABLE XH2COST(IRRRE, IRRRI) 'H2 transmission cost between regions (calculated from exported quantity) (Money/MWh)'
          CL0       CL1       CL2       CL3       CL4       CL5       CL6       CL7       CL8       CL9
                                                                                                       
CL0       0.0            0.000001            0.000001            0.000001                      0.000001
CL1                 0.0  0.000001                                                                      
CL2  0.000001  0.000001       0.0            0.000001  0.000001                                0.000001
CL3                                     0.0                      0.000001                              
CL4  0.000001            0.000001                 0.0                                0.000001          
CL5                      0.000001                                                                      
CL6  0.000001                      0.000001                           0.0  0.000001                    
CL7                                                              0.000001                              
CL8                                          0.000001                                                  
CL9  0.000001            0.000001                                                                      
;