TABLE XH2COST(IAAAE, IAAAI) 'H2 transmission cost between regions (calculated from exported quantity) (Money/MWh)'
          CL0_A     CL1_A     CL2_A     CL3_A     CL4_A     CL5_A     CL6_A     CL7_A     CL8_A     CL9_A
                                                                                                         
CL0_A       0.0            0.000001  0.000001  0.000001                                                  
CL1_A                 0.0                      0.000001                      0.000001  0.000001  0.000001
CL2_A  0.000001                 0.0                      0.000001                                        
CL3_A  0.000001                           0.0                                                            
CL4_A  0.000001  0.000001                           0.0                                          0.000001
CL5_A                      0.000001                                0.000001                              
CL6_A                                                    0.000001                                        
CL7_A            0.000001                                                                                
CL8_A            0.000001                                                                                
CL9_A            0.000001                      0.000001                                               0.0
;