                                                                                                                                                                                                                            
$onembedded                                                                                                                                                                                                                 
SET RRRAAA(RRR,AAA)    "Areas in regions"                                                                                                                                                                                   
/                                                                                                                                                                                                                           

AL . AL_IDVU-HOTWTR
AT . AT_IDVU-HOTWTR
BA . BA_IDVU-HOTWTR
BE . BE_IDVU-HOTWTR
BG . BG_IDVU-HOTWTR
CH . CH_IDVU-HOTWTR
CZ . CZ_IDVU-HOTWTR
DE . DE_IDVU-HOTWTR
DK . DK_IDVU-HOTWTR
EE . EE_IDVU-HOTWTR
ES . ES_IDVU-HOTWTR
FI . FI_IDVU-HOTWTR
FR . FR_IDVU-HOTWTR
GR . GR_IDVU-HOTWTR
HR . HR_IDVU-HOTWTR
HU . HU_IDVU-HOTWTR
IE . IE_IDVU-HOTWTR
IT . IT_IDVU-HOTWTR
LT . LT_IDVU-HOTWTR
LU . LU_IDVU-HOTWTR
LV . LV_IDVU-HOTWTR
ME . ME_IDVU-HOTWTR
MK . MK_IDVU-HOTWTR
NL . NL_IDVU-HOTWTR
NO . NO_IDVU-HOTWTR
PL . PL_IDVU-HOTWTR
PT . PT_IDVU-HOTWTR
RO . RO_IDVU-HOTWTR
RS . RS_IDVU-HOTWTR
SE . SE_IDVU-HOTWTR
SI . SI_IDVU-HOTWTR
SK . SK_IDVU-HOTWTR
UK . UK_IDVU-HOTWTR

AL . AL_IDVU-SPACEHEAT
AT . AT_IDVU-SPACEHEAT
BA . BA_IDVU-SPACEHEAT
BE . BE_IDVU-SPACEHEAT
BG . BG_IDVU-SPACEHEAT
CH . CH_IDVU-SPACEHEAT
CZ . CZ_IDVU-SPACEHEAT
DE . DE_IDVU-SPACEHEAT
DK . DK_IDVU-SPACEHEAT
EE . EE_IDVU-SPACEHEAT
ES . ES_IDVU-SPACEHEAT
FI . FI_IDVU-SPACEHEAT
FR . FR_IDVU-SPACEHEAT
GR . GR_IDVU-SPACEHEAT
HR . HR_IDVU-SPACEHEAT
HU . HU_IDVU-SPACEHEAT
IE . IE_IDVU-SPACEHEAT
IT . IT_IDVU-SPACEHEAT
LT . LT_IDVU-SPACEHEAT
LU . LU_IDVU-SPACEHEAT
LV . LV_IDVU-SPACEHEAT
ME . ME_IDVU-SPACEHEAT
MK . MK_IDVU-SPACEHEAT
NL . NL_IDVU-SPACEHEAT
NO . NO_IDVU-SPACEHEAT
PL . PL_IDVU-SPACEHEAT
PT . PT_IDVU-SPACEHEAT
RO . RO_IDVU-SPACEHEAT
RS . RS_IDVU-SPACEHEAT
SE . SE_IDVU-SPACEHEAT
SI . SI_IDVU-SPACEHEAT
SK . SK_IDVU-SPACEHEAT
UK . UK_IDVU-SPACEHEAT     

                                                                                                                                                                                                  
$label    NO_INDIVUSERS_AAA                                                                                                                                                                                                 
/;                                                                                                                                                                                                                          
$offembedded                                                                                                                                                                                                                
