SET CCCRRRAAA 'All geographical entities (CCC + RRR + AAA)'                                                                                                                                       
/                                                                                                                                                                                                 

AL_IDVU-HOTWTR
AT_IDVU-HOTWTR
BA_IDVU-HOTWTR
BE_IDVU-HOTWTR
BG_IDVU-HOTWTR
CH_IDVU-HOTWTR
CZ_IDVU-HOTWTR
DE_IDVU-HOTWTR
DK_IDVU-HOTWTR
EE_IDVU-HOTWTR
ES_IDVU-HOTWTR
FI_IDVU-HOTWTR
FR_IDVU-HOTWTR
GR_IDVU-HOTWTR
HR_IDVU-HOTWTR
HU_IDVU-HOTWTR
IE_IDVU-HOTWTR
IT_IDVU-HOTWTR
LT_IDVU-HOTWTR
LU_IDVU-HOTWTR
LV_IDVU-HOTWTR
ME_IDVU-HOTWTR
MK_IDVU-HOTWTR
NL_IDVU-HOTWTR
NO_IDVU-HOTWTR
PL_IDVU-HOTWTR
PT_IDVU-HOTWTR
RO_IDVU-HOTWTR
RS_IDVU-HOTWTR
SE_IDVU-HOTWTR
SI_IDVU-HOTWTR
SK_IDVU-HOTWTR
UK_IDVU-HOTWTR
AL_IDVU-SPACEHEAT
AT_IDVU-SPACEHEAT
BA_IDVU-SPACEHEAT
BE_IDVU-SPACEHEAT
BG_IDVU-SPACEHEAT
CH_IDVU-SPACEHEAT
CZ_IDVU-SPACEHEAT
DE_IDVU-SPACEHEAT
DK_IDVU-SPACEHEAT
EE_IDVU-SPACEHEAT
ES_IDVU-SPACEHEAT
FI_IDVU-SPACEHEAT
FR_IDVU-SPACEHEAT
GR_IDVU-SPACEHEAT
HR_IDVU-SPACEHEAT
HU_IDVU-SPACEHEAT
IE_IDVU-SPACEHEAT
IT_IDVU-SPACEHEAT
LT_IDVU-SPACEHEAT
LU_IDVU-SPACEHEAT
LV_IDVU-SPACEHEAT
ME_IDVU-SPACEHEAT
MK_IDVU-SPACEHEAT
NL_IDVU-SPACEHEAT
NO_IDVU-SPACEHEAT
PL_IDVU-SPACEHEAT
PT_IDVU-SPACEHEAT
RO_IDVU-SPACEHEAT
RS_IDVU-SPACEHEAT
SE_IDVU-SPACEHEAT
SI_IDVU-SPACEHEAT
SK_IDVU-SPACEHEAT
UK_IDVU-SPACEHEAT 

$label NO_INDIVUSERS_AAA                                                                                                                                                                          
                                                                                                                                                                                                  
                                                                                                                                                                                                  
/;                                                                                                                                                                                                
                                                                                                                                                                                                  
