SET RRRAAA(RRR,AAA) "Areas in regions"                                                                  
/                                                                                                       
DE                                                                  .    DE_A                        
FI                                                                  .    FI_A                        
DK                                                                  .    DK_A                        
NO                                                                  .    NO_A   
SE                                                                  .    SE_A                           
EE                                                                  .    EE_A                           
LT                                                                  .    LT_A                           
LV                                                                  .    LV_A                           
NL                                                                  .    NL_A                           
PL                                                                  .    PL_A                           
UK                                                                  .    UK_A                           
BE                                                                  .    BE_A                           
FR                                                                  .    FR_A                                                                                                                           
IT                                                                  .    IT_A                           
CH                                                                  .    CH_A                           
AT                                                                  .    AT_A                           
CZ                                                                  .    CZ_A                           
ES                                                                  .    ES_A                           
PT                                                                  .    PT_A                           
SK                                                                  .    SK_A                           
HU                                                                  .    HU_A                           
SI                                                                  .    SI_A                           
HR                                                                  .    HR_A                           
RO                                                                  .    RO_A                           
BG                                                                  .    BG_A                           
GR                                                                  .    GR_A                           
IE                                                                  .    IE_A                           
LU                                                                  .    LU_A                           
AL                                                                  .    AL_A                           
ME                                                                  .    ME_A                           
MK                                                                  .    MK_A                           
BA                                                                  .    BA_A                           
RS                                                                  .    RS_A                           
TR                                                                  .    TR_A                           
MT                                                                  .    MT_A                           
CY                                                                  .    CY_A                           

AL . AL_OFF
BA . BA_OFF
BE . BE_OFF
DE . DE_OFF
DK . DK_OFF
EE . EE_OFF
ES . ES_OFF
FI . FI_OFF
FR . FR_OFF
GR . GR_OFF
IE . IE_OFF
IT . IT_OFF
LT . LT_OFF
LV . LV_OFF
ME . ME_OFF
NL . NL_OFF
NO . NO_OFF
PL . PL_OFF
PT . PT_OFF
RO . RO_OFF
SE . SE_OFF
SI . SI_OFF
UK . UK_OFF
                                                                                                        
/;                                                                                                      
                                                                                                        
