TABLE SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, SUBTECH_GROUP) 'Subtechnology group capacity restriction by geography (MW)'
                                     RG1 RG1_OFF1 RG1_OFF2 RG1_OFF3 RG1_OFF4 RG1_OFF5            RG2  RG2_OFF1 RG2_OFF2 RG2_OFF3 RG2_OFF4 RG2_OFF5            RG3 RG3_OFF1 RG3_OFF2 RG3_OFF3 RG3_OFF4 RG3_OFF5
                                                                                                                                                                                                              
AL . SOLARPV                      9000.0                                                     13000.0                                                          EPS                                             
AL . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                      EPS      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
AL . WINDTURBINE_ONSHORE           200.0                                                       800.0                                                       1000.0                                             
AT . SOLARPV                  31471.4625                                                  31471.4625                                                          EPS                                             
AT . WINDTURBINE_ONSHORE           965.1                                                      3860.4                                                       4825.5                                             
BA . SOLARPV                     12000.0                                                     24350.0                                                          EPS                                             
BA . WINDTURBINE_ONSHORE           200.0                                                       800.0                                                       1000.0                                             
BE . SOLARPV                    10000.55                                                    19229.55                                                          EPS                                             
BE . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                   7900.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
BE . WINDTURBINE_ONSHORE           890.0                                                      3560.0                                                       4450.0                                             
BG . SOLARPV                     41800.0                                                     51800.0                                                          EPS                                             
BG . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                   2103.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
BG . WINDTURBINE_ONSHORE           340.0                                                      1360.0                                                       1700.0                                             
CH . SOLARPV                10000.531838                                                48494.531838                                                          EPS                                             
CH . WINDTURBINE_ONSHORE           100.0                                                       400.0                                                        500.0                                             
CZ . SOLARPV                   10000.275                                                   49420.275                                                          EPS                                             
CZ . WINDTURBINE_ONSHORE          1884.6                                                      7538.4                                                       9423.0                                             
DE . SOLARPV                  199227.675                                                  199227.675                                                          EPS                                             
DE . WINDTURBINE_OFFSHORE                   200.0      EPS      EPS      EPS      EPS                  58919.0      EPS      EPS      EPS      EPS                 16281.0      EPS      EPS      EPS      EPS
DE . WINDTURBINE_ONSHORE    11485.872289                                                41874.719322                                                      49350.0                                             
DK . SOLARPV                     18496.4                                                     34496.4                                                          EPS                                             
DK . WINDTURBINE_OFFSHORE                   440.0      EPS      EPS      EPS      EPS                  85000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
DK . WINDTURBINE_ONSHORE           800.0                                                      3200.0                                                       8500.0                                             
EE . SOLARPV                   13019.025                                                   13019.025                                                          EPS                                             
EE . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  18700.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
EE . WINDTURBINE_ONSHORE          1840.0                                                      7360.0                                                       9200.0                                             
ES . SOLARPV                32136.784494                                                96410.353483                                                190820.706965                                             
ES . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  10000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
ES . WINDTURBINE_ONSHORE         53500.0                                                    214000.0                                                     267500.0                                             
FI . SOLARPV                   14694.375                                                   14694.375                                                          EPS                                             
FI . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  34600.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
FI . WINDTURBINE_ONSHORE          1500.0                                                      6000.0                                                       7500.0                                             
FR . SOLARPV                35136.784494                                               105410.353483                                                230820.706965                                             
FR . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  53300.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
FR . WINDTURBINE_ONSHORE         10120.0                                                     40480.0                                                      50600.0                                             
GR . SOLARPV                     40000.0                                                     66000.0                                                          EPS                                             
GR . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                   9596.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
GR . WINDTURBINE_ONSHORE     1152.520325                                                 4610.081301                                                  5762.601626                                             
HR . SOLARPV                     15700.0                                                     26700.0                                                          EPS                                             
HR . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                   3998.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
HR . WINDTURBINE_ONSHORE           690.0                                                      2760.0                                                       3450.0                                             
HU . SOLARPV                     30200.0                                                     43200.0                                                          EPS                                             
HU . WINDTURBINE_ONSHORE            96.9                                                       240.0                                                        300.0                                             
IE . SOLARPV                15333.333333                                                15333.333333                                                          EPS                                             
IE . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  20611.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
IE . WINDTURBINE_ONSHORE     1358.909772                                                 5435.639088                                                   6794.54886                                             
IT . SOLARPV                33366.287107                                               100098.861321                                                150197.722641                                             
IT . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  10000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
IT . WINDTURBINE_ONSHORE          3869.2                                                     15476.8                                                      19346.0                                             
LT . SOLARPV                    44821.35                                                    44821.35                                                          EPS                                             
LT . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                   2000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
LT . WINDTURBINE_ONSHORE          2140.0                                                      8560.0                                                      10700.0                                             
LU . SOLARPV                       500.0                                                       500.0                                                          EPS                                             
LU . WINDTURBINE_ONSHORE       66.116067                                                  264.464267                                                   330.580334                                             
LV . SOLARPV                     22873.5                                                     22873.5                                                          EPS                                             
LV . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  12800.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
LV . WINDTURBINE_ONSHORE          2330.0                                                      9320.0                                                      11650.0                                             
ME . SOLARPV                      5400.0                                                      6400.0                                                          EPS                                             
ME . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                      EPS      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
ME . WINDTURBINE_ONSHORE            40.0                                                       160.0                                                        200.0                                             
MK . SOLARPV                      8500.0                                                     12000.0                                                          EPS                                             
MK . WINDTURBINE_ONSHORE            40.0                                                       160.0                                                        200.0                                             
NL . SOLARPV                     24036.3                                                     24036.3                                                          EPS                                             
NL . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                    631.0  67700.0      EPS      EPS      EPS                     EPS               EPS      EPS      EPS
NL . WINDTURBINE_ONSHORE          1030.0                                                      4120.0                                                       5150.0                                             
NO . SOLARPV                11645.650164                                                11645.650164                                                          EPS                                             
NO . WINDTURBINE_OFFSHORE                   290.0      EPS      EPS      EPS      EPS                  35249.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
NO . WINDTURBINE_ONSHORE          1400.0                                                 5790.464566                                                       7000.0                                             
PL . SOLARPV                    30000.85                                                    50000.85                                                          EPS                                             
PL . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  11000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
PL . WINDTURBINE_ONSHORE         15000.0                                                     60000.0                                                      75000.0                                             
PT . SOLARPV                 12680.61219                                                 28680.61219                                                          EPS                                             
PT . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  10000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
PT . WINDTURBINE_ONSHORE          2400.0                                                      9600.0                                                      12000.0                                             
RO . SOLARPV                     40000.0                                                    103600.0                                                          EPS                                             
RO . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  22420.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
RO . WINDTURBINE_ONSHORE          2040.0                                                      8160.0                                                      10200.0                                             
ROW . SOLARPV                    54215.0                                               122311.666667                                                     232290.0                                             
ROW . WINDTURBINE_OFFSHORE                    EPS      EPS      EPS      EPS      EPS                  12400.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
ROW . WINDTURBINE_ONSHORE        11491.0                                                     45796.0                                                      57016.0                                             
RS . SOLARPV                       500.0                                                       500.0                                                          EPS                                             
RS . WINDTURBINE_ONSHORE           119.1                                                      258.05                                                        200.0                                             
SE . SOLARPV                     29314.8                                                     29314.8                                                          EPS                                             
SE . WINDTURBINE_OFFSHORE                     EPS      EPS      EPS      EPS      EPS                  43000.0      EPS      EPS      EPS      EPS                     EPS      EPS      EPS      EPS      EPS
SE . WINDTURBINE_ONSHORE          3500.0                                                     14000.0                                                      17500.0                                             
SI . SOLARPV                      7600.0                                                      9600.0                                                          EPS                                             
SI . WINDTURBINE_ONSHORE            60.0                                                       240.0                                                        300.0                                             
SK . SOLARPV                     22950.0                                                     22950.0                                                          EPS                                             
SK . WINDTURBINE_ONSHORE           210.0                                                       840.0                                                       1050.0                                             
UK . SOLARPV                    27251.34                                                    81754.02                                                    163508.04                                             
UK . WINDTURBINE_OFFSHORE                     EPS      EPS    108.0      EPS    200.0                 150000.0   2176.0   4030.0   2285.0   7079.6                     EPS                                    
UK . WINDTURBINE_ONSHORE         12000.0                                                     48000.0                                                      60000.0                                             
;

SUBTECHGROUPKPOT(CCCRRRAAA, 'WINDTURBINE_ONSHORE', 'RG2')$(SUM(SUBTECH_GROUP, SUBTECHGROUPKPOT(CCCRRRAAA, 'WINDTURBINE_ONSHORE', SUBTECH_GROUP)) > 0) = SUM(SUBTECH_GROUP, SUBTECHGROUPKPOT(CCCRRRAAA, 'WINDTURBINE_ONSHORE', SUBTECH_GROUP));
SUBTECHGROUPKPOT(CCCRRRAAA, 'SOLARPV', 'RG2')$(SUM(SUBTECH_GROUP, SUBTECHGROUPKPOT(CCCRRRAAA, 'SOLARPV', SUBTECH_GROUP)) > 0) = SUM(SUBTECH_GROUP, SUBTECHGROUPKPOT(CCCRRRAAA, 'SOLARPV', SUBTECH_GROUP));
SUBTECHGROUPKPOT(CCCRRRAAA, 'WINDTURBINE_OFFSHORE', 'RG2_OFF1')$(SUM(SUBTECH_GROUP, SUBTECHGROUPKPOT(CCCRRRAAA, 'WINDTURBINE_OFFSHORE', SUBTECH_GROUP)) > 0) = SUM(SUBTECH_GROUP, SUBTECHGROUPKPOT(CCCRRRAAA, 'WINDTURBINE_OFFSHORE', SUBTECH_GROUP));



SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG1') = EPS; 

SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG3') = EPS; 

SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG1_OFF1') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG1_OFF2') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG1_OFF3') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG1_OFF4') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG1_OFF5') = EPS;

SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG2_OFF2') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG2_OFF3') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG2_OFF4') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG2_OFF5') = EPS;            
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG3_OFF1') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG3_OFF2') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG3_OFF3') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG3_OFF4') = EPS; 
SUBTECHGROUPKPOT(CCCRRRAAA, TECH_GROUP, 'RG3_OFF5') = EPS;