TABLE XCOST(IRRRE, IRRRI) 'Transmission cost between regions (Money/MWh)'
        CL0     CL1     CL2     CL3     CL4     CL5     CL6     CL7     CL8     CL9
                                                                                   
CL0     0.0  0.0001                  0.0001                          0.0001  0.0001
CL1  0.0001     0.0  0.0001          0.0001                          0.0001        
CL2          0.0001     0.0                  0.0001                                
CL3                             0.0          0.0001                                
CL4  0.0001  0.0001                     0.0                                        
CL5                  0.0001  0.0001             0.0  0.0001                        
CL6                                          0.0001          0.0001                
CL7                                                  0.0001                        
CL8  0.0001  0.0001                                                                
CL9  0.0001                                                                        
;