TABLE XINVCOST(YYY, IRRRE, IRRRI) 'Investment cost in new transmission capacity, default: INF or 0: no investment, EPS or positive: possible with stated cost (Money/MW)'
                      CL0            CL1           CL2            CL3            CL4           CL5          CL6           CL7           CL8           CL9
                                                                                                                                                         
2050 . CL0            0.0                 33251.700244  530405.582856   93378.274587                                                                     
2050 . CL1                           0.0                               101913.892001                             87845.034584  66723.558503  73839.429668
2050 . CL2   33251.700244                          0.0                                23726.681487                                                       
2050 . CL3  530405.582856                                         0.0                                                                                    
2050 . CL4   93378.274587  101913.892001                                         0.0                                                         109365.41356
2050 . CL5                                23726.681487                                              5555.556863                                          
2050 . CL6                                                                             5555.556863                                                       
2050 . CL7                  87845.034584                                                                                                                 
2050 . CL8                  66723.558503                                                                                                                 
2050 . CL9                  73839.429668                                109365.41356                                                                  0.0
;