TABLE XINVCOST(YYY, IRRRE, IRRRI) 'Investment cost in new transmission capacity, default: INF or 0: no investment, EPS or positive: possible with stated cost (Money/MW)'
                     CL0           CL1           CL2            CL3           CL4            CL5           CL6          CL7           CL8           CL9
                                                                                                                                                       
2050 . CL0           0.0  99271.942478                               94927.051182                                            82016.243039  87845.034584
2050 . CL1  99271.942478           0.0  93378.274587                 110307.89364                                            61625.996991              
2050 . CL2                93378.274587           0.0                                60817.036005                                                       
2050 . CL3                                                      0.0                530405.582856                                                       
2050 . CL4  94927.051182  110307.89364                                        0.0                                                                      
2050 . CL5                              60817.036005  530405.582856                          0.0  23726.681487                                         
2050 . CL6                                                                          23726.681487                5555.556863                            
2050 . CL7                                                                                         5555.556863                                         
2050 . CL8  82016.243039  61625.996991                                                                                                                 
2050 . CL9  87845.034584                                                                                                                               
;