TABLE XINVCOST(YYY, IRRRE, IRRRI) 'Investment cost in new transmission capacity, default: INF or 0: no investment, EPS or positive: possible with stated cost (Money/MW)'
                      CL0            CL1            CL2            CL3            CL4           CL5            CL6           CL7           CL8           CL9
                                                                                                                                                            
2050 . CL0            0.0                  68920.927778                 126210.975175                 58952.744101                              81344.850436
2050 . CL1                           0.0  106462.683025                                                                                                     
2050 . CL2   68920.927778  106462.683025            0.0                  110178.47606  66723.558503                                             92178.490682
2050 . CL3                                                         0.0                               530405.582856                                          
2050 . CL4  126210.975175                  110178.47606                           0.0                                             53852.120281              
2050 . CL5                                 66723.558503                                                                                                     
2050 . CL6   58952.744101                                530405.582856                                         0.0  21130.806541                            
2050 . CL7                                                                                            21130.806541                                          
2050 . CL8                                                               53852.120281                                                                       
2050 . CL9   81344.850436                  92178.490682                                                                                                     
;